### ISSUE TITLE
Action fails when `${{ job.status }}` is used on cancelled jobs

### ISSUE THREAD

**Issue by khitrenovich** [myrotvorets/set-commit-status-action#320]
When final update uses `${{ job.status }}` as recommended in README - 
```
      - name: Set final commit status
        uses: myrotvorets/set-commit-status-action@master
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          context: Publish NPM package
```
and the workflow is cancelled, the action will fail - 
```
Run myrotvorets/set-commit-status-action@1.1.5
  with:
    sha: <redacted>
    status: cancelled
    token: ***
    allowForks: false
    targetUrl: <redacted>
    context: <redacted>
Error: state must be one of "error", "failure", "pending", "success"
```
