### ISSUE TITLE
Add ability to avoid printing targetUrl 

### ISSUE THREAD

**Issue by spetrosi** [myrotvorets/set-commit-status-action#663]
Sometimes I want to add a status that some platform is skipped.
In this case, I want to avoid printing *Details* button completely.

For example, here is a screenshot of an external action that states that the workflow is skipped and doesn't display *Details* button, and the workflow status created by set-commit-status-action that prints the unwanted *Details* button.

![Screenshot from 2024-07-24 17-27-33](https://github.com/user-attachments/assets/6504e991-2460-479f-92af-e863e62ad240)

**Comment by spetrosi** [comment]
Setting `targetUrl: ""` solves this!
I am sorry for noise.

**Comment by myrotvorets-team** [comment]
Did you try setting `targetUrl` to an empty string?

```yaml
    uses: myrotvorets/set-commit-status-action@v2.0.1
    with:
        targetUrl: ''
```
