### ISSUE TITLE
Can't see the updates commit status in the pull request

### ISSUE THREAD

**Issue by NoamGaash** [myrotvorets/set-commit-status-action#765]
Hi, thank you for maintaining this project!

We're trying to use this action to add a commit status that links to a playwright test reporter we have uploaded -
https://github.com/hasadna/open-bus-map-search/actions/runs/12035311399/job/33554660712?pr=951
but it seems like it doesn't update [the pull request on github](https://github.com/hasadna/open-bus-map-search/pull/951):
![image](https://github.com/user-attachments/assets/6379d7a1-b596-41d7-91e8-8b77be3b2393)
![image](https://github.com/user-attachments/assets/ee10e983-6583-403d-915c-64a3b24a5d97)

Are we doing something wrong?
```
      - name: Set test results
        uses: myrotvorets/set-commit-status-action@master
        if: always() && ${{ env.AWS_KEY_ID }}
        with:
          sha: ${{ github.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          description: 'Playwright html report with traces'
          status: ${{needs.test.result}}
          context: 'Test results'
          targetUrl: 'https://s3.amazonaws.com/noam-gaash.co.il/${{ github.run_id }}/open-bus/${{ github.sha }}/test-results/index.html'
```
Thank you :pray:
